### ISSUE TITLE
java.util.date vs java.time

### ISSUE THREAD

**Issue by Flooooooooooorian** [rinaehyun/Flight-Tracker#30]
https://github.com/rinaehyun/Flight-Tracker/blob/2a84e75b16dc21ef952fbf4d9b4a9d70dbc04e62/backend/src/main/java/com/rhyun/backend/globalexception/GlobalExceptionHandler.java#L20

Hey du solltest auf jeden Fall hier eine Klasse aus dem java.time package nutzen z.B. `Instant`

**Comment by rinaehyun** [comment]
Danke, ich habe mit Instant aktualisiert 👍
